<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>LCARS</RootNamespace>
    <AssemblyName>LCARS</AssemblyName>
    <StartupObject>LCARS.MainWindow</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Page Include="MainWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\themes\Base.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="MainWindow.xaml.vb" />
  </ItemGroup>

</Project>
