"""
LCARS Code Generator - DevTools Module

Генератор коду для LCARS компонентів.
Створює готовий Python код на базі шаблонів.
"""

from typing import Dict, List, Any
import json
from pathlib import Path

class LCARSCodeGenerator:
    """Generator for LCARS interface code"""
    
    def __init__(self):
        self.templates_dir = Path(__file__).parent / "samples" / "code_snippets"
        self.templates_dir.mkdir(parents=True, exist_ok=True)
        
    def generate_widget_class(self, class_name: str, base_class: str = "QWidget", 
                             era: str = "LCARS_25TH", components: List[Dict] = None) -> str:
        """Generate a complete widget class"""
        components = components or []
        
        imports = [
            "from PyQt6.QtWidgets import QWidget, QVBoxLayout, QHBoxLayout, QLabel, QPushButton",
            "from PyQt6.QtCore import Qt, pyqtSignal",
            "from PyQt6.QtGui import QFont",
            f"from lcars.themes.lcars_palette import LCARSEra, get_era_palette"
        ]
        
        code_lines = [
            '"""',
            f'Auto-generated LCARS {class_name}',
            'Generated by LCARS DevTools Code Generator',
            '"""',
            '',
            *imports,
            '',
            f'class {class_name}({base_class}):',
            '    """LCARS-styled widget"""',
            '    ',
            '    def __init__(self, parent=None):',
            '        super().__init__(parent)',
            f'        self.era_palette = get_era_palette(LCARSEra.{era})',
            '        self.setup_ui()',
            '        self.apply_lcars_style()',
            '    ',
            '    def setup_ui(self):',
            '        """Setup the user interface"""',
            '        self.main_layout = QVBoxLayout(self)',
            '        self.main_layout.setContentsMargins(10, 10, 10, 10)',
            '        ',
        ]
        
        # Add components
        for comp in components:
            comp_type = comp.get('type', 'QLabel')
            comp_name = comp.get('name', 'widget')
            comp_text = comp.get('text', '')
            
            code_lines.extend([
                f'        # {comp_name.replace("_", " ").title()}',
                f'        self.{comp_name} = {comp_type}("{comp_text}")',
                f'        self.main_layout.addWidget(self.{comp_name})',
                '        ',
            ])
        
        code_lines.extend([
            '    def apply_lcars_style(self):',
            '        """Apply LCARS styling"""',
            '        self.setStyleSheet(f"""',
            '            QWidget {{',
            '                background-color: {self.era_palette["background"]};',
            '                color: {self.era_palette["text"]};',
            '                font-family: "Courier New";',
            '            }}',
            '            QPushButton {{',
            '                background-color: {self.era_palette["button_colors"][0]};',
            '                color: {self.era_palette["background"]};',
            '                border: none;',
            '                border-radius: 12px;',
            '                padding: 10px;',
            '                font-weight: bold;',
            '            }}',
            '            QPushButton:hover {{',
            '                background-color: {self.era_palette["button_colors"][1]};',
            '            }}',
            '            QLabel {{',
            '                font-size: 14px;',
            '                padding: 5px;',
            '            }}',
            '        """)',
        ])
        
        return '\n'.join(code_lines)
    
    def generate_main_window(self, window_name: str, era: str = "LCARS_25TH") -> str:
        """Generate a main window template"""
        return f'''"""
LCARS Main Window - {window_name}
Generated by LCARS DevTools Code Generator
"""

import sys
from PyQt6.QtWidgets import QApplication, QMainWindow, QWidget, QVBoxLayout
from PyQt6.QtCore import Qt
from lcars.themes.lcars_palette import LCARSEra, get_era_palette

class {window_name}(QMainWindow):
    """LCARS Main Window"""
    
    def __init__(self):
        super().__init__()
        self.era_palette = get_era_palette(LCARSEra.{era})
        self.setWindowTitle("LCARS Interface")
        self.setMinimumSize(1200, 800)
        
        # Remove window frame for LCARS look
        self.setWindowFlags(Qt.WindowType.FramelessWindowHint)
        
        self.setup_ui()
        self.apply_lcars_style()
    
    def setup_ui(self):
        """Setup the main interface"""
        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        
        layout = QVBoxLayout(central_widget)
        layout.setContentsMargins(0, 0, 0, 0)
        
        # Add your widgets here
        
    def apply_lcars_style(self):
        """Apply LCARS window styling"""
        self.setStyleSheet(f"""
            QMainWindow {{
                background-color: {{self.era_palette["background"]}};
            }}
        """)

def main():
    app = QApplication(sys.argv)
    
    window = {window_name}()
    window.show()
    
    sys.exit(app.exec())

if __name__ == '__main__':
    main()
'''
    
    def generate_plugin_template(self, plugin_name: str) -> str:
        """Generate a plugin template"""
        return f'''"""
LCARS Plugin: {plugin_name}
Generated by LCARS DevTools Code Generator
"""

from lcars.core.plugin_system import LCARSPlugin

class {plugin_name}Plugin(LCARSPlugin):
    """LCARS Plugin: {plugin_name}"""
    
    def __init__(self):
        super().__init__()
        self.name = "{plugin_name}"
        self.version = "1.0.0"
        self.description = "Auto-generated LCARS plugin"
    
    def initialize(self):
        """Initialize the plugin"""
        print(f"Initializing {{self.name}} plugin...")
        
    def activate(self):
        """Activate the plugin"""
        print(f"Activating {{self.name}} plugin...")
        
    def deactivate(self):
        """Deactivate the plugin"""
        print(f"Deactivating {{self.name}} plugin...")
    
    def get_menu_items(self):
        """Return menu items for this plugin"""
        return [
            {{"name": f"{{self.name}} Action", "callback": self.plugin_action}}
        ]
    
    def plugin_action(self):
        """Main plugin action"""
        print(f"{{self.name}} action executed!")

# Plugin registration
def get_plugin_class():
    return {plugin_name}Plugin
'''

def save_template(name: str, content: str, template_type: str = "widget"):
    """Save generated code as template"""
    templates_dir = Path(__file__).parent / "samples" / "code_snippets"
    templates_dir.mkdir(parents=True, exist_ok=True)
    
    file_path = templates_dir / f"{template_type}_{name.lower()}.py"
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Template saved: {file_path}")
    return file_path

if __name__ == '__main__':
    # Example usage
    generator = LCARSCodeGenerator()
    
    # Generate a widget
    widget_code = generator.generate_widget_class(
        "LCARSControlPanel",
        components=[
            {"type": "QLabel", "name": "status_label", "text": "System Status"},
            {"type": "QPushButton", "name": "power_button", "text": "POWER"},
            {"type": "QPushButton", "name": "reset_button", "text": "RESET"}
        ]
    )
    
    save_template("control_panel", widget_code, "widget")
    print("Example widget generated!")